### ISSUE TITLE
Please add a README that explains this project

### ISSUE THREAD

**Issue by luzpaz** [denismikulich91/SurfaceMineDesignWB#1]
TIA!

**Comment by luzpaz** [comment]
Thanks you! Any chance you can populate with Images when operational ?

**Comment by denismikulich91** [comment]
Hi mate! Yeah, I want to finish main geometry generation first (hopefully within November) and will add a detailed guide and better described future development plans into README. Also there will be short videos with tool usage cases.

**Comment by denismikulich91** [comment]
All done. The root README has a list of features I plan to implement within the Workbench. Once its ready there will be a link with the detailed description. I have just added one describing the basic design logic

**Comment by luzpaz** [comment]
Great! Can you add a background section ?
